### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by ghost** [fmahoudeau/MiCT-Net-PyTorch#6]
**Excuse me, how can I solve this problem**：
python train.py --model mictresnet --version v1 --backbone resnet18 --lr 1e-2 --weight-decay 5e-4 --dropout 0.5 --batch-size 112 --base-size 192 --crop-size 160 --split 1 --checkname MiCTResNet_V1 --crop-vid 16 --epochs 120 --pretrained --lr-scheduler step --lr-step 80
=> creating output/ucf101/mictresnet/MiCTResNet_V1/
Namespace(backbone='resnet18', base_size=192, batch_size=112, checkname='MiCTResNet_V1', crop_size=160, crop_vid=16, cuda=True, data_folder='/home/y/MiCT/Datasets/', dataset='ucf101', dropout=0.5, epochs=120, eval=False, ft=False, gpu_id=0, lr=0.01, lr_scheduler='step', lr_step=80, model='mictresnet', model_zoo=None, momentum=0.9, no_cuda=False, no_val=False, pretrained=True, resume='', seed=1, split=1, start_epoch=0, test_batch_size=112, test_folder=None, version='v1', weight_decay=0.0005, workers=8)
Compute device: cuda:0
Loading UCF101 train1.csv
9537it [00:00, 254159.06it/s]
Loading UCF101 val1.csv
3783it [00:00, 239066.04it/s]
Total number of parameters: 16051685
Using step LR scheduler
  0%|                                                    | 0/85 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 221, in <module>
    trainer.training(epoch)
  File "train.py", line 148, in training
    for i, (video, target) in enumerate(tbar):
  File "/home/y/Anaconda/envs/mm/lib/python3.7/site-packages/tqdm/std.py", line 1127, in __iter__
    for obj in iterable:
  File "/home/y/Anaconda/envs/mm/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/y/Anaconda/envs/mm/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/y/Anaconda/envs/mm/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/y/Anaconda/envs/mm/lib/python3.7/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/y/Anaconda/envs/mm/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/y/Anaconda/envs/mm/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/y/Anaconda/envs/mm/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "../../mictnet/datasets/ucf101.py", line 115, in __getitem__
    vid = self._train_transform(vid)
  File "../../mictnet/datasets/ucf101.py", line 188, in _train_transform
    w, h = vid[0].size
**IndexError: list index out of range**

**Comment by fmahoudeau** [comment]
Hello, apparently the list of video frames is empty. Have you checked the source directory ? Are the images properly loaded by the **_load_sample** function ?

**Comment by mengban** [comment]
I met the same problem.  The main reason is that I didn't generate the images files correctly. You can check your **images** folder to   ensure your images have been generated.

**Comment by ghost** [comment]
Thank you for your reply. I have successfully solved this problem.

> 您好，显然视频帧列表为空。您是否检查了源目录？**_load_sample**函数是否正确加载了图像？

Thank you for your reply. I have successfully solved this problem

**Comment by ghost** [comment]
> 我遇到了同样的问题。主要原因是我没有正确生成图像文件。您可以检查**图像**文件夹以确保已生成图像。

Thank you, it has been successfully solved
